"""add product_name and condition to items

Revision ID: 08f80d9670f9
Revises: da0c6b0aa866
Create Date: 2026-05-17 01:51:03.749568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08f80d9670f9'
down_revision: Union[str, Sequence[str], None] = 'da0c6b0aa866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('product_name', sa.String(), nullable=True))
    op.add_column('items', sa.Column('condition', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'condition')
    op.drop_column('items', 'product_name')
    # ### end Alembic commands ###
