"""Initial schema

Revision ID: 0d6653f9f889
Revises: 
Create Date: 2026-05-08 06:30:36.913827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d6653f9f889'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auction_houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('website_key', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('buyer_premium_pct', sa.Float(), nullable=False),
    sa.Column('cash_discount_pct', sa.Float(), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.Column('terms_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_auction_houses_id'), 'auction_houses', ['id'], unique=False)
    op.create_index(op.f('ix_auction_houses_website_key'), 'auction_houses', ['website_key'], unique=True)
    op.create_table('auctions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auction_house_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('location_address', sa.String(), nullable=True),
    sa.Column('location_city', sa.String(), nullable=True),
    sa.Column('location_state', sa.String(), nullable=True),
    sa.Column('location_zip', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['auction_house_id'], ['auction_houses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auctions_external_id'), 'auctions', ['external_id'], unique=False)
    op.create_index(op.f('ix_auctions_id'), 'auctions', ['id'], unique=False)
    op.create_table('condition_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auction_house_id', sa.Integer(), nullable=False),
    sa.Column('raw_pattern', sa.String(), nullable=False),
    sa.Column('ebay_condition_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['auction_house_id'], ['auction_houses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_condition_map_id'), 'condition_map', ['id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auction_house_id', sa.Integer(), nullable=False),
    sa.Column('auction_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('lot_number', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('current_bid', sa.Float(), nullable=True),
    sa.Column('bid_count', sa.Integer(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('raw_condition', sa.String(), nullable=True),
    sa.Column('normalized_condition_id', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('mpn', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['auction_house_id'], ['auction_houses.id'], ),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_external_id'), 'items', ['external_id'], unique=False)
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_table('ebay_sample_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('query_signature', sa.String(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('trimmed_median', sa.Float(), nullable=True),
    sa.Column('iqr', sa.Float(), nullable=True),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('ttl', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ebay_sample_cache_id'), 'ebay_sample_cache', ['id'], unique=False)
    op.create_index(op.f('ix_ebay_sample_cache_item_id'), 'ebay_sample_cache', ['item_id'], unique=False)
    op.create_index(op.f('ix_ebay_sample_cache_query_signature'), 'ebay_sample_cache', ['query_signature'], unique=False)
    op.create_table('valuations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('sample_cache_id', sa.Integer(), nullable=True),
    sa.Column('est_market_value', sa.Float(), nullable=True),
    sa.Column('market_adjustment_factor_applied', sa.Float(), nullable=True),
    sa.Column('max_bid_for_target_roi', sa.Float(), nullable=True),
    sa.Column('target_roi_pct', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['sample_cache_id'], ['ebay_sample_cache.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_valuations_id'), 'valuations', ['id'], unique=False)
    op.create_index(op.f('ix_valuations_item_id'), 'valuations', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_valuations_item_id'), table_name='valuations')
    op.drop_index(op.f('ix_valuations_id'), table_name='valuations')
    op.drop_table('valuations')
    op.drop_index(op.f('ix_ebay_sample_cache_query_signature'), table_name='ebay_sample_cache')
    op.drop_index(op.f('ix_ebay_sample_cache_item_id'), table_name='ebay_sample_cache')
    op.drop_index(op.f('ix_ebay_sample_cache_id'), table_name='ebay_sample_cache')
    op.drop_table('ebay_sample_cache')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_index(op.f('ix_items_external_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_condition_map_id'), table_name='condition_map')
    op.drop_table('condition_map')
    op.drop_index(op.f('ix_auctions_id'), table_name='auctions')
    op.drop_index(op.f('ix_auctions_external_id'), table_name='auctions')
    op.drop_table('auctions')
    op.drop_index(op.f('ix_auction_houses_website_key'), table_name='auction_houses')
    op.drop_index(op.f('ix_auction_houses_id'), table_name='auction_houses')
    op.drop_table('auction_houses')
    # ### end Alembic commands ###
