"""add vehicle fields to research and bid items

Revision ID: 1084d4f0f523
Revises: 4485bb11170d
Create Date: 2026-05-18 00:07:52.070503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1084d4f0f523'
down_revision: Union[str, Sequence[str], None] = '4485bb11170d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bid_items', sa.Column('vin', sa.String(), nullable=True))
    op.add_column('bid_items', sa.Column('vehicle_year', sa.Integer(), nullable=True))
    op.add_column('bid_items', sa.Column('vehicle_make', sa.String(), nullable=True))
    op.add_column('bid_items', sa.Column('vehicle_model', sa.String(), nullable=True))
    op.add_column('bid_items', sa.Column('vehicle_trim', sa.String(), nullable=True))
    op.create_index(op.f('ix_bid_items_vin'), 'bid_items', ['vin'], unique=False)
    op.add_column('research_items', sa.Column('vin', sa.String(), nullable=True))
    op.add_column('research_items', sa.Column('vehicle_year', sa.Integer(), nullable=True))
    op.add_column('research_items', sa.Column('vehicle_make', sa.String(), nullable=True))
    op.add_column('research_items', sa.Column('vehicle_model', sa.String(), nullable=True))
    op.add_column('research_items', sa.Column('vehicle_trim', sa.String(), nullable=True))
    op.create_index(op.f('ix_research_items_vin'), 'research_items', ['vin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_items_vin'), table_name='research_items')
    op.drop_column('research_items', 'vehicle_trim')
    op.drop_column('research_items', 'vehicle_model')
    op.drop_column('research_items', 'vehicle_make')
    op.drop_column('research_items', 'vehicle_year')
    op.drop_column('research_items', 'vin')
    op.drop_index(op.f('ix_bid_items_vin'), table_name='bid_items')
    op.drop_column('bid_items', 'vehicle_trim')
    op.drop_column('bid_items', 'vehicle_model')
    op.drop_column('bid_items', 'vehicle_make')
    op.drop_column('bid_items', 'vehicle_year')
    op.drop_column('bid_items', 'vin')
    # ### end Alembic commands ###
