"""add is_archived to items

Revision ID: 17607b8a5c83
Revises: 9ec7591be48f
Create Date: 2026-05-16 00:28:00.196541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17607b8a5c83'
down_revision: Union[str, Sequence[str], None] = '9ec7591be48f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'is_archived')
    # ### end Alembic commands ###
