"""Add work queue phase 1 models

Revision ID: 2618c47e5de8
Revises: 588f98419d5b
Create Date: 2026-05-16 05:39:08.793622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2618c47e5de8'
down_revision: Union[str, Sequence[str], None] = '588f98419d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packaging_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('box_cost', sa.Float(), nullable=True),
    sa.Column('void_fill_cost', sa.Float(), nullable=True),
    sa.Column('addon_cost', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_packaging_configurations_id'), 'packaging_configurations', ['id'], unique=False)
    op.create_table('inventory_parent_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_item_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('hammer_price', sa.Float(), nullable=True),
    sa.Column('buyer_premium_pct', sa.Float(), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.Column('misc_fees', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_parent_lots_id'), 'inventory_parent_lots', ['id'], unique=False)
    op.create_table('inventory_cost_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=True),
    sa.Column('parent_lot_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['parent_lot_id'], ['inventory_parent_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_cost_line_items_id'), 'inventory_cost_line_items', ['id'], unique=False)
    op.add_column('inventory_items', sa.Column('parent_lot_id', sa.Integer(), nullable=True))
    op.add_column('inventory_items', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('inventory_items', sa.Column('length', sa.Float(), nullable=True))
    op.add_column('inventory_items', sa.Column('width', sa.Float(), nullable=True))
    op.add_column('inventory_items', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('inventory_items', sa.Column('storage_location', sa.String(), nullable=True))
    op.add_column('inventory_items', sa.Column('tracking_number', sa.String(), nullable=True))
    op.add_column('inventory_items', sa.Column('qr_code_url', sa.String(), nullable=True))
    op.create_foreign_key(None, 'inventory_items', 'inventory_parent_lots', ['parent_lot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory_items', type_='foreignkey')
    op.drop_column('inventory_items', 'qr_code_url')
    op.drop_column('inventory_items', 'tracking_number')
    op.drop_column('inventory_items', 'storage_location')
    op.drop_column('inventory_items', 'height')
    op.drop_column('inventory_items', 'width')
    op.drop_column('inventory_items', 'length')
    op.drop_column('inventory_items', 'weight')
    op.drop_column('inventory_items', 'parent_lot_id')
    op.drop_index(op.f('ix_inventory_cost_line_items_id'), table_name='inventory_cost_line_items')
    op.drop_table('inventory_cost_line_items')
    op.drop_index(op.f('ix_inventory_parent_lots_id'), table_name='inventory_parent_lots')
    op.drop_table('inventory_parent_lots')
    op.drop_index(op.f('ix_packaging_configurations_id'), table_name='packaging_configurations')
    op.drop_table('packaging_configurations')
    # ### end Alembic commands ###
