"""Add UserAuctionCredential

Revision ID: 2e2bc7f336c1
Revises: 99ed106a074e
Create Date: 2026-05-13 05:06:42.492704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e2bc7f336c1'
down_revision: Union[str, Sequence[str], None] = '99ed106a074e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_auction_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('auction_house', sa.String(), nullable=False),
    sa.Column('encrypted_cookies', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'auction_house', name='uq_user_auction_house')
    )
    op.create_index(op.f('ix_user_auction_credentials_auction_house'), 'user_auction_credentials', ['auction_house'], unique=False)
    op.create_index(op.f('ix_user_auction_credentials_id'), 'user_auction_credentials', ['id'], unique=False)
    op.create_index(op.f('ix_user_auction_credentials_user_id'), 'user_auction_credentials', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_auction_credentials_user_id'), table_name='user_auction_credentials')
    op.drop_index(op.f('ix_user_auction_credentials_id'), table_name='user_auction_credentials')
    op.drop_index(op.f('ix_user_auction_credentials_auction_house'), table_name='user_auction_credentials')
    op.drop_table('user_auction_credentials')
    # ### end Alembic commands ###
