"""Add Work Queue Phase 1 fields

Revision ID: 35ac5ad1bfad
Revises: 2f08ab2ed22f
Create Date: 2026-05-16 11:14:58.057114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35ac5ad1bfad'
down_revision: Union[str, Sequence[str], None] = '2f08ab2ed22f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('shipping_carrier', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_items', 'shipping_carrier')
    # ### end Alembic commands ###
