"""split items into research and bid

Revision ID: 4485bb11170d
Revises: b027cc1e90f2
Create Date: 2026-05-18 04:45:30.631602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4485bb11170d'
down_revision: Union[str, Sequence[str], None] = 'b027cc1e90f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bid_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auction_house_id', sa.Integer(), nullable=False),
    sa.Column('auction_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('lot_number', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('current_bid_amount', sa.Float(), nullable=True),
    sa.Column('user_bid_amount', sa.Float(), nullable=True),
    sa.Column('user_proxy_bid', sa.Float(), nullable=True),
    sa.Column('user_bid_status', sa.String(), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_hidden_from_active', sa.Boolean(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('search_queries', sa.JSON(), nullable=True),
    sa.Column('normalized_condition_id', sa.String(), nullable=True),
    sa.Column('processing_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['auction_house_id'], ['auction_houses.id'], ),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_items_external_id'), 'bid_items', ['external_id'], unique=False)
    op.create_index(op.f('ix_bid_items_id'), 'bid_items', ['id'], unique=False)
    op.create_table('research_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auction_house_id', sa.Integer(), nullable=False),
    sa.Column('auction_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('lot_number', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('current_bid', sa.Float(), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('search_queries', sa.JSON(), nullable=True),
    sa.Column('normalized_condition_id', sa.String(), nullable=True),
    sa.Column('is_watched', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('processing_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['auction_house_id'], ['auction_houses.id'], ),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_items_external_id'), 'research_items', ['external_id'], unique=False)
    op.create_index(op.f('ix_research_items_id'), 'research_items', ['id'], unique=False)
    op.add_column('ebay_sample_cache', sa.Column('research_item_id', sa.Integer(), nullable=True))
    op.add_column('ebay_sample_cache', sa.Column('bid_item_id', sa.Integer(), nullable=True))
    op.alter_column('ebay_sample_cache', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_ebay_sample_cache_bid_item_id'), 'ebay_sample_cache', ['bid_item_id'], unique=False)
    op.create_index(op.f('ix_ebay_sample_cache_research_item_id'), 'ebay_sample_cache', ['research_item_id'], unique=False)
    op.create_foreign_key(None, 'ebay_sample_cache', 'bid_items', ['bid_item_id'], ['id'])
    op.create_foreign_key(None, 'ebay_sample_cache', 'research_items', ['research_item_id'], ['id'])
    op.add_column('inventory_parent_lots', sa.Column('source_bid_item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inventory_parent_lots', 'bid_items', ['source_bid_item_id'], ['id'])
    op.add_column('valuation_details', sa.Column('research_item_id', sa.Integer(), nullable=True))
    op.add_column('valuation_details', sa.Column('bid_item_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_valuation_details_bid_item_id'), 'valuation_details', ['bid_item_id'], unique=False)
    op.create_index(op.f('ix_valuation_details_research_item_id'), 'valuation_details', ['research_item_id'], unique=False)
    op.create_foreign_key(None, 'valuation_details', 'bid_items', ['bid_item_id'], ['id'])
    op.create_foreign_key(None, 'valuation_details', 'research_items', ['research_item_id'], ['id'])
    op.add_column('valuations', sa.Column('research_item_id', sa.Integer(), nullable=True))
    op.add_column('valuations', sa.Column('bid_item_id', sa.Integer(), nullable=True))
    op.alter_column('valuations', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_valuations_bid_item_id'), 'valuations', ['bid_item_id'], unique=False)
    op.create_index(op.f('ix_valuations_research_item_id'), 'valuations', ['research_item_id'], unique=False)
    op.create_foreign_key(None, 'valuations', 'bid_items', ['bid_item_id'], ['id'])
    op.create_foreign_key(None, 'valuations', 'research_items', ['research_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'valuations', type_='foreignkey')
    op.drop_constraint(None, 'valuations', type_='foreignkey')
    op.drop_index(op.f('ix_valuations_research_item_id'), table_name='valuations')
    op.drop_index(op.f('ix_valuations_bid_item_id'), table_name='valuations')
    op.alter_column('valuations', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('valuations', 'bid_item_id')
    op.drop_column('valuations', 'research_item_id')
    op.drop_constraint(None, 'valuation_details', type_='foreignkey')
    op.drop_constraint(None, 'valuation_details', type_='foreignkey')
    op.drop_index(op.f('ix_valuation_details_research_item_id'), table_name='valuation_details')
    op.drop_index(op.f('ix_valuation_details_bid_item_id'), table_name='valuation_details')
    op.drop_column('valuation_details', 'bid_item_id')
    op.drop_column('valuation_details', 'research_item_id')
    op.drop_constraint(None, 'inventory_parent_lots', type_='foreignkey')
    op.drop_column('inventory_parent_lots', 'source_bid_item_id')
    op.drop_constraint(None, 'ebay_sample_cache', type_='foreignkey')
    op.drop_constraint(None, 'ebay_sample_cache', type_='foreignkey')
    op.drop_index(op.f('ix_ebay_sample_cache_research_item_id'), table_name='ebay_sample_cache')
    op.drop_index(op.f('ix_ebay_sample_cache_bid_item_id'), table_name='ebay_sample_cache')
    op.alter_column('ebay_sample_cache', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('ebay_sample_cache', 'bid_item_id')
    op.drop_column('ebay_sample_cache', 'research_item_id')
    op.drop_index(op.f('ix_research_items_id'), table_name='research_items')
    op.drop_index(op.f('ix_research_items_external_id'), table_name='research_items')
    op.drop_table('research_items')
    op.drop_index(op.f('ix_bid_items_id'), table_name='bid_items')
    op.drop_index(op.f('ix_bid_items_external_id'), table_name='bid_items')
    op.drop_table('bid_items')
    # ### end Alembic commands ###
