"""Add Bidding and Valuation tables

Revision ID: 588f98419d5b
Revises: d5cab93897f2
Create Date: 2026-05-15 14:31:05.943296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '588f98419d5b'
down_revision: Union[str, Sequence[str], None] = 'd5cab93897f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_bid_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('current_bid_amount', sa.Float(), nullable=True),
    sa.Column('user_bid_amount', sa.Float(), nullable=True),
    sa.Column('user_proxy_bid', sa.Float(), nullable=True),
    sa.Column('user_bid_status', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    op.create_index(op.f('ix_user_bid_activity_id'), 'user_bid_activity', ['id'], unique=False)
    op.create_table('valuation_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_cache_id', sa.Integer(), nullable=False),
    sa.Column('sample_listings', sa.JSON(), nullable=True),
    sa.Column('avg_asking_price', sa.Float(), nullable=True),
    sa.Column('median_asking_price', sa.Float(), nullable=True),
    sa.Column('price_range_low', sa.Float(), nullable=True),
    sa.Column('price_range_high', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['sample_cache_id'], ['ebay_sample_cache.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_cache_id')
    )
    op.create_index(op.f('ix_valuation_details_id'), 'valuation_details', ['id'], unique=False)
    op.add_column('items', sa.Column('images', sa.JSON(), nullable=True))
    op.add_column('items', sa.Column('shipping_cost_est', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'shipping_cost_est')
    op.drop_column('items', 'images')
    op.drop_index(op.f('ix_valuation_details_id'), table_name='valuation_details')
    op.drop_table('valuation_details')
    op.drop_index(op.f('ix_user_bid_activity_id'), table_name='user_bid_activity')
    op.drop_table('user_bid_activity')
    # ### end Alembic commands ###
