"""Add ebay listings and orders

Revision ID: 69b8517dcc5b
Revises: 2618c47e5de8
Create Date: 2026-05-16 00:00:50.676779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b8517dcc5b'
down_revision: Union[str, Sequence[str], None] = '2618c47e5de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ebay_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=True),
    sa.Column('ebay_item_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('watchers', sa.Integer(), nullable=True),
    sa.Column('listed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ebay_listings_ebay_item_id'), 'ebay_listings', ['ebay_item_id'], unique=False)
    op.create_index(op.f('ix_ebay_listings_id'), 'ebay_listings', ['id'], unique=False)
    op.create_table('ebay_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ebay_order_id', sa.String(), nullable=False),
    sa.Column('ebay_listing_id', sa.Integer(), nullable=True),
    sa.Column('buyer_username', sa.String(), nullable=True),
    sa.Column('total_paid', sa.Float(), nullable=True),
    sa.Column('ebay_fees', sa.Float(), nullable=True),
    sa.Column('shipping_paid_by_buyer', sa.Float(), nullable=True),
    sa.Column('actual_shipping_cost', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ebay_listing_id'], ['ebay_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ebay_orders_ebay_order_id'), 'ebay_orders', ['ebay_order_id'], unique=False)
    op.create_index(op.f('ix_ebay_orders_id'), 'ebay_orders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ebay_orders_id'), table_name='ebay_orders')
    op.drop_index(op.f('ix_ebay_orders_ebay_order_id'), table_name='ebay_orders')
    op.drop_table('ebay_orders')
    op.drop_index(op.f('ix_ebay_listings_id'), table_name='ebay_listings')
    op.drop_index(op.f('ix_ebay_listings_ebay_item_id'), table_name='ebay_listings')
    op.drop_table('ebay_listings')
    # ### end Alembic commands ###
