"""Add dual transit tracking fields

Revision ID: 1a2b3c4d5e6f
Revises: 
Create Date: 2024-05-16 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a2b3c4d5e6f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('shipping_method', sa.String(), nullable=True))
    op.add_column('inventory_items', sa.Column('local_pickup_address', sa.String(), nullable=True))
    op.add_column('inventory_items', sa.Column('local_pickup_deadline', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_items', 'local_pickup_deadline')
    op.drop_column('inventory_items', 'local_pickup_address')
    op.drop_column('inventory_items', 'shipping_method')
    # ### end Alembic commands ###