"""add product_name and condition to inventory_items

Revision ID: b027cc1e90f2
Revises: 08f80d9670f9
Create Date: 2026-05-17 01:52:12.128322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b027cc1e90f2'
down_revision: Union[str, Sequence[str], None] = '08f80d9670f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('product_name', sa.String(), nullable=True))
    op.add_column('inventory_items', sa.Column('condition', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_items', 'condition')
    op.drop_column('inventory_items', 'product_name')
    # ### end Alembic commands ###
