"""Add category and tags to Item model

Revision ID: c9eb247f266f
Revises: f4fffa2e4334
Create Date: 2026-05-08 10:41:02.199877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9eb247f266f'
down_revision: Union[str, Sequence[str], None] = 'f4fffa2e4334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('category', sa.String(), nullable=True))
    op.add_column('items', sa.Column('tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'tags')
    op.drop_column('items', 'category')
    # ### end Alembic commands ###
