"""add_unique_constraint_to_valuation_item_id

Revision ID: d5cab93897f2
Revises: fccabdea2a06
Create Date: 2026-05-15 19:40:53.956366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5cab93897f2'
down_revision: Union[str, Sequence[str], None] = 'fccabdea2a06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_valuations_item_id'), table_name='valuations')
    op.create_index(op.f('ix_valuations_item_id'), 'valuations', ['item_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_valuations_item_id'), table_name='valuations')
    op.create_index(op.f('ix_valuations_item_id'), 'valuations', ['item_id'], unique=False)
    # ### end Alembic commands ###
