"""add search_queries to Item

Revision ID: e73cfcd5af37
Revises: f5136061f091
Create Date: 2026-05-11 18:15:35.471424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e73cfcd5af37'
down_revision: Union[str, Sequence[str], None] = 'f5136061f091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('search_queries', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'search_queries')
    # ### end Alembic commands ###
