"""Add vehicle columns

Revision ID: f23456789abc
Revises: f5136061f091
Create Date: 2026-05-11 23:59:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f23456789abc'
down_revision = 'e73cfcd5af37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('vin', sa.String(), nullable=True))
    op.add_column('items', sa.Column('vehicle_year', sa.Integer(), nullable=True))
    op.add_column('items', sa.Column('vehicle_make', sa.String(), nullable=True))
    op.add_column('items', sa.Column('vehicle_model', sa.String(), nullable=True))
    op.add_column('items', sa.Column('vehicle_trim', sa.String(), nullable=True))
    op.create_index(op.f('ix_items_vin'), 'items', ['vin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_vin'), table_name='items')
    op.drop_column('items', 'vehicle_trim')
    op.drop_column('items', 'vehicle_model')
    op.drop_column('items', 'vehicle_make')
    op.drop_column('items', 'vehicle_year')
    op.drop_column('items', 'vin')
    # ### end Alembic commands ###
