"""Add inventory items model

Revision ID: f4fffa2e4334
Revises: 618fa815ab01
Create Date: 2026-05-08 08:44:04.570177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4fffa2e4334'
down_revision: Union[str, Sequence[str], None] = '618fa815ab01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('drafted_title', sa.String(), nullable=True),
    sa.Column('drafted_description', sa.String(), nullable=True),
    sa.Column('ebay_category_id', sa.String(), nullable=True),
    sa.Column('buy_price', sa.Float(), nullable=True),
    sa.Column('estimated_price', sa.Float(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_barcode'), 'inventory_items', ['barcode'], unique=False)
    op.create_index(op.f('ix_inventory_items_id'), 'inventory_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_items_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_barcode'), table_name='inventory_items')
    op.drop_table('inventory_items')
    # ### end Alembic commands ###
